<?php
// WARNING: DO NOT EDIT THIS FILE !

if ( session_id() == '' ) session_start();
ob_start();

// get main config
require ("config.php");

// get prepared text
require ("/includes/predefined.php" );

// get functions
require ("/includes/functions.php" );
?>